In [73]:
import tools
import numpy as np
import Part1

def paa(T, c):
    """
    PAA cuts a trajectory T of size n into N = n/c pieces,
    For each piece i, it computes the average point Pi as representative point
    """
    if c>len(T): 
        raise Exception("Samples number cannot be bigger than number of points")
    ans = []
    rg = int(len(T)/c)
    rem = len(T)%c
    for idx in range(rg):
        ans.append(np.average(T[idx*c:(idx+1)*c], axis=0))
    if rem>0:
        ans.append(np.average(T[rg*c:rg*c+rem]))
    return ans

def pdtw(T1, T2, c):
    sT1 = paa(T1, c)
    sT2 = paa(T2, c)
    _dist_matrix, warp_path=Part1.dtw(sT1, sT2)
    
    return warp_path

In [26]:
Data_Highway = tools.read_trajectories("../data/highway.csv")
data = tools.reconstruct(Data_Highway)

In [75]:
curr = np.array([0.0,0.0])
c=2
l = len(data[0])
print(l)
rg = int(l/c)
rem = l%c
for idx in range(rg):
    print(data[0][idx*c:(idx+1)*c])
    print(np.average(data[0][idx*c:(idx+1)*c], axis=0))
if rem>0:
    print(data[0][rg*c:rg*c+rem])

paa(data[0], 2)

18
[[4.585165010891318, 52.36617100155285], [8.39230843982636, 52.932287911444966]]
[ 6.48873673 52.64922946]
[[9.22486753569087, 50.995742355737065], [11.463424594269528, 47.14214750643927]]
[10.34414606 49.06894493]
[[15.415455171750672, 50.74621412040997], [20.66701770507021, 54.89248977438185]]
[18.04123644 52.81935195]
[[25.48279516815153, 53.674060842588865], [25.292317973950237, 51.420745176370026]]
[25.38755657 52.54740301]
[[33.56161725709149, 50.974900271848824], [35.97137612657253, 51.332055574958474]]
[34.76649669 51.15347792]
[[37.82580239709949, 50.43629146567749], [45.634207449935886, 51.98448809544414]]
[41.73000492 51.21038978]
[[46.90657263658545, 49.44300557897457], [52.004766061367654, 50.503477936855404]]
[49.45566935 49.97324176]
[[55.15812711391811, 50.838642962021616], [55.725459768693035, 52.78323989805623]]
[55.44179344 51.81094143]
[[61.76856218048111, 51.416603560546605], [64.74936921924899, 49.92976786820428]]
[63.2589657  50.67318571]


[array([ 6.48873673, 52.64922946]),
 array([10.34414606, 49.06894493]),
 array([18.04123644, 52.81935195]),
 array([25.38755657, 52.54740301]),
 array([34.76649669, 51.15347792]),
 array([41.73000492, 51.21038978]),
 array([49.45566935, 49.97324176]),
 array([55.44179344, 51.81094143]),
 array([63.2589657 , 50.67318571])]

In [33]:
paa(data[0], 2)

[] 0


TypeError: can only concatenate list (not "int") to list